// Code generated by MockGen. DO NOT EDIT.
// Source: service/service.go
//
// Generated by this command:
//
//	mockgen --source=service/service.go --destination=mocks/service_mock.go --package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	model "github.com/rajendrasatpute/ways-to-create-rest-apis/go/sample-gin-api/model"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetCityInfo mocks base method.
func (m *MockService) GetCityInfo(cityName string) model.Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCityInfo", cityName)
	ret0, _ := ret[0].(model.Response)
	return ret0
}

// GetCityInfo indicates an expected call of GetCityInfo.
func (mr *MockServiceMockRecorder) GetCityInfo(cityName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCityInfo", reflect.TypeOf((*MockService)(nil).GetCityInfo), cityName)
}
