version: "3.9"

services:
  sample-db:
    image: mysql:8.3.0
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./data-dump.sql:/docker-entrypoint-initdb.d/data-dump.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  springboot-app:
    depends_on:
      sample-db:
        condition: service_healthy
    build: ../java/sample-springboot-api
    restart: on-failure
    env_file: .env
    ports:
      - $SPRING_BOOT_LOCAL_PORT:$SPRING_BOOT_DOCKER_PORT
    environment:
      - MYSQLDB_HOST=$MYSQLDB_HOST
      - MYSQLDB_USER=$MYSQLDB_USER
      - MYSQLDB_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQLDB_DATABASE=$MYSQLDB_DATABASE
      - MYSQLDB_LOCAL_PORT=$MYSQLDB_LOCAL_PORT
      - MYSQLDB_DOCKER_PORT=$MYSQLDB_DOCKER_PORT
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  springmvc-app:
    depends_on:
      sample-db:
        condition: service_healthy
    build: ../java/sample-springmvc-api
    restart: on-failure
    env_file: .env
    ports:
      - $SPRING_MVC_LOCAL_PORT:$SPRING_MVC_DOCKER_PORT
    environment:
      - MYSQLDB_HOST=$MYSQLDB_HOST
      - MYSQLDB_USER=$MYSQLDB_USER
      - MYSQLDB_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQLDB_DATABASE=$MYSQLDB_DATABASE
      - MYSQLDB_LOCAL_PORT=$MYSQLDB_LOCAL_PORT
      - MYSQLDB_DOCKER_PORT=$MYSQLDB_DOCKER_PORT
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  express-app:
    depends_on:
      sample-db:
        condition: service_healthy
    build: ../javascript/express
    restart: on-failure
    env_file: .env
    ports:
      - $EXPRESS_LOCAL_PORT:$EXPRESS_DOCKER_PORT
    environment:
      - MYSQLDB_HOST=$MYSQLDB_HOST
      - MYSQLDB_USER=$MYSQLDB_USER
      - MYSQLDB_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQLDB_DATABASE=$MYSQLDB_DATABASE
    stdin_open: true
    tty: true

  gin-app:
    depends_on:
      sample-db:
        condition: service_healthy
    build: ../go/sample-gin-api
    restart: on-failure
    env_file: .env
    ports:
      - $GO_GIN_LOCAL_PORT:$GO_GIN_DOCKER_PORT
    environment:
      - MYSQLDB_HOST=$MYSQLDB_HOST
      - MYSQLDB_USER=$MYSQLDB_USER
      - MYSQLDB_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQLDB_DATABASE=$MYSQLDB_DATABASE
    stdin_open: true
    tty: true

  nginx:
    image: nginx:1.25.3
    restart: unless-stopped
    ports:
      - $NGINX_LOCAL_PORT:$NGINX_DOCKER_PORT
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - springboot-app
      - express-app
